version: '3.8'

services:


  frontend:
    build:
      context: ./painel-rpa
      dockerfile: Dockerfile
    container_name: onesid-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - onesid-net

networks:
  onesid-net:
    driver: bridge